In [1]:
import pandas as pd
import numpy as np

In [8]:
from SimpleLR import MySimpleLR

In [24]:
lr = MySimpleLR()
df

Temperature     Revenue
0      24.566884  534.799028
1      26.005191  625.190122
2      27.790554  660.632289
3      20.595335  487.706960
4      11.503498  316.240194
..           ...         ...
495    22.274899  524.746364
496    32.893092  755.818399
497    12.588157  306.090719
498    22.362402  566.217304
499    28.957736  655.660388

[500 rows x 2 columns]

In [25]:
df = pd.read_csv("IceCreamData.csv")
x = df.iloc[:,0].values.reshape(-1,1)
y = df.iloc[:,1].values.reshape(-1,1)

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [28]:
x_test.shape

(100, 1)

In [29]:
lr.fit(x_train,y_train)

[21.5133908]
[43.73357869]


In [30]:
from sklearn.linear_model import LinearRegression

In [31]:
sklr = LinearRegression()

In [33]:
sklr.fit(x_train,y_train)

LinearRegression()

In [34]:
sklr.coef_

array([[21.5133908]])

In [35]:
sklr.intercept_

array([43.73357869])

In [39]:
y_hat = lr.predict(x_test)
y_hat

array([[698.3385558 ],
       [653.32331149],
       [664.73027451],
       [450.5192845 ],
       [665.47469743],
       [441.36861407],
       [584.06540609],
       [623.82532723],
       [667.48717467],
       [468.72433832],
       [546.82733151],
       [443.41191785],
       [622.95162777],
       [377.64639971],
       [367.0607334 ],
       [945.67057977],
       [893.79551974],
       [694.45445099],
       [546.05047608],
       [420.58523672],
       [391.08500303],
       [597.0141581 ],
       [283.23582775],
       [655.50055011],
       [380.98796154],
       [412.31810124],
       [371.05055651],
       [510.23910289],
       [479.70270426],
       [456.68206658],
       [640.1157508 ],
       [281.65224383],
       [314.1894674 ],
       [470.01363777],
       [559.72453055],
       [539.75091165],
       [307.72368191],
       [508.65180339],
       [571.43237276],
       [732.25599161],
       [440.44010989],
       [494.39422767],
       [567.56536766],
       [443

In [48]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [49]:
mean_absolute_error(y_test,y_hat)

18.30321353010285

In [53]:
mse = mean_squared_error(y_test,y_hat)
mse

528.2150684519324

In [54]:
np.sqrt(mse)

22.98292993619248

In [55]:
r2 = r2_score(y_test,y_hat)
r2

0.9837324255882577